"""Data transfer objects used in instructions/messages."""

from dataclasses import dataclass
from enum import Enum


@dataclass
class Coordinates:
    """X/Y coordinates."""
    x: int
    y: int


class MessageType(Enum):
    """The type of an instruction."""
    NewRobot = 'new-robot'
    Asteroid = 'asteroid'
    Move = 'move'
    Robot = 'robot'


class BearingType(Enum):
    """Legal Robot bearings."""
    North = 'north'
    South = 'south'
    East = 'east'
    West = 'west'


class MovementType(Enum):
    """Legal Robot movements."""
    Left = 'turn-left'
    Right = 'turn-right'
    Forward = 'move-forward'


@dataclass(frozen=True)
class AsteroidMessage:
    """A Message stating the size of an Asteroid."""
    size: Coordinates


@dataclass(frozen=True)
class NewRobotMessage:
    """A new robot message."""
    position: Coordinates
    bearing: BearingType


@dataclass(frozen=True)
class MoveMessage:
    """A movement message."""
    movement: MovementType


@dataclass(frozen=True)
class RobotMessage:
    """A message generated by a Robot."""
    position: Coordinates
    bearing: BearingType
